apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-vote-redis
  labels:
    name: redis
    type: redis

spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis
        type: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      app: redis
