apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-vote-result
  labels:
    name: deploy-vote-result
    type: frontend

spec:
  template:
    metadata:
      name: vote-result
      labels:
        app: vote-result
        type: frontend
    spec:
      containers:
        - name: vote-result-node
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: vote-result