apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-vote-front
  labels:
    name: deploy-vote-front
    type: frontend

spec:
  template:
    metadata:
      name: vote-front
      labels:
        app: vote-front
        type: frontend
    spec:
      containers:
        - name: vote-front-python
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: vote-front