apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-vote-worker
  labels:
    name: deploy-vote-worker
    type: app-worker

spec:
  template:
    metadata:
      name: vote-worker
      labels:
        app: vote-worker
        type: worker
    spec:
      containers:
        - name: vote-worker
          image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    matchLabels:
      app: vote-worker
