apiVersion: v1
kind: Service
metadata:
  name: service-vote-front
  labels:
    name: service-vote-front

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 3002
  selector:
    app: vote-front