apiVersion: v1
kind: Service
metadata:
  name: service-vote-result
  labels:
    name: service-vote-result

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30003
  selector:
    app: vote-result